package per.zc.system.model;

import java.util.List;

import per.zc.system.model.base.BaseSysMenu;

/**
 * Generated by JFinal.
 * 菜单
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {
	public static final SysMenu dao = new SysMenu().dao();
	
	public List<SysMenu> findAll(){
		String sql = "select * from sys_menu order by  sort asc";
		return find(sql);
	}
}
