package per.zc.system.model;

import java.util.List;

import per.zc.system.model.base.BaseSysOrg;

/**
 * Generated by JFinal.
 * 部门
 */
@SuppressWarnings("serial")
public class SysOrg extends BaseSysOrg<SysOrg> {
	public static final SysOrg dao = new SysOrg().dao();
	

	public  List<SysOrg> getChildren(){
		return get("children");
	}
}
