package per.zc.system.model;

import per.zc.system.model.base.BaseSysOrg;

/**
 * Generated by JFinal.
 * 部门
 */
@SuppressWarnings("serial")
public class SysOrg extends BaseSysOrg<SysOrg> {
	public static final SysOrg dao = new SysOrg().dao();
}
