package per.zc.system.model;

import per.zc.system.model.base.BaseSysRoleMenu;

/**
 * Generated by JFinal.
 * 角色 菜单表
 */
@SuppressWarnings("serial")
public class SysRoleMenu extends BaseSysRoleMenu<SysRoleMenu> {
	public static final SysRoleMenu dao = new SysRoleMenu().dao();
}
