package per.zc.system.model;

import per.zc.system.model.base.BaseSysRole;

/**
 * Generated by JFinal.
 * 角色
 */
@SuppressWarnings("serial")
public class SysRole extends BaseSysRole<SysRole> {
	public static final SysRole dao = new SysRole().dao();
}
