package per.zc.system.model;

import per.zc.system.model.base.BaseSysUser;

/**
 * Generated by JFinal.
 * 用户表
 */
@SuppressWarnings("serial")
public class SysUser extends BaseSysUser<SysUser> {
	public static final SysUser dao = new SysUser().dao();
}
